data:extend({
    {
        type = "string-setting",
        name = "F077ET-chunk-subdivision",
        setting_type = "runtime-global",
        default_value = "x32",
        allowed_values = { "x32", "x16", "x8" },
        order = "a",
    },
    {
        type = "int-setting",
        name = "F077ET-base-update-delay",
        setting_type = "runtime-global",
        default_value = 030,
        minimum_value = 001,
        order = "b-a",
    },
    {
        type = "int-setting",
        name = "F077ET-base-processing-amount",
        setting_type = "runtime-global",
        default_value = 01,
        order = "b-b",
    },
    {
        type = "int-setting",
        name = "F077ET-long-update-delay",
        setting_type = "runtime-global",
        default_value = 150,
        minimum_value = 001,
        order = "c-a",
    },
    {
        type = "int-setting",
        name = "F077ET-long-processing-amount",
        setting_type = "runtime-global",
        default_value = 02,
        order = "c-b",
    },
    {
        type = "bool-setting",
        name = "F077ET-comp-base",
        setting_type = "startup",
        default_value = true,
        order = "d-a",
    },
    {
        type = "bool-setting",
        name = "F077ET-comp-space-age",
        setting_type = "startup",
        default_value = true,
        order = "d-b",
    },
    {
        type = "bool-setting",
        name = "F077ET-comp-space-exploration",
        setting_type = "startup",
        default_value = true,
        order = "d-c",
    },
    {
        type = "bool-setting",
        name = "F077ET-comp-krastorio2",
        setting_type = "startup",
        default_value = true,
        order = "d-d",
    },
    {
        type = "bool-setting",
        name = "F077ET-comp-krastorio2-spaced-out",
        setting_type = "startup",
        default_value = true,
        order = "d-e",
    },
    {
        type = "bool-setting",
        name = "F077ET-comp-dectorio",
        setting_type = "startup",
        default_value = true,
        order = "d-f",
    },
    {
        type = "bool-setting",
        name = "F077ET-debug-mode",
        setting_type = "startup",
        default_value = false,
        order = "e",
    },
})
