data:extend({
    {
        type = "string-setting",
        name = "F077ET-chunk-subdivision",
        setting_type = "runtime-global",
        default_value = "x32",
        allowed_values = { "x32", "x16", "x8" },
        order = "a",
    },
    {
        type = "string-setting",
        name = "F077ET-base-update-delay",
        setting_type = "runtime-global",
        default_value = "0.50 seconds",
        allowed_values = { "0.50 seconds", "0.75 seconds", "1.00 seconds" },
        order = "b-a",
    },
    {
        type = "int-setting",
        name = "F077ET-base-processing-amount",
        setting_type = "runtime-global",
        default_value = 01,
        order = "b-b",
    },
    {
        type = "string-setting",
        name = "F077ET-long-update-delay",
        setting_type = "runtime-global",
        default_value = "2.50 seconds",
        allowed_values = { "2.50 seconds", "5.00 seconds", "7.50 seconds" },
        order = "c-a",
    },
    {
        type = "int-setting",
        name = "F077ET-long-processing-amount",
        setting_type = "runtime-global",
        default_value = 02,
        order = "c-b",
    },
    {
        type = "bool-setting",
        name = "F077ET-debug-mode",
        setting_type = "startup",
        default_value = false,
        order = "d",
    },
})
